from pathlib import Path
import re
from datetime import datetime
from strategy_ideation_engine.config import settings, logger
from strategy_ideation_engine.schemas.hypothesis import TradingHypothesis

class MarkdownExporter:
    """
    Phase 6: Professional Export Module.
    Converts structured hypotheses into human-readable investment reports.
    """
    def __init__(self, export_dir: str = None):
        self.export_dir = Path(export_dir or settings.EXPORT_DIR)
        self.export_dir.mkdir(parents=True, exist_ok=True)

    def export(self, hypothesis: TradingHypothesis) -> str:
        """Generates a Markdown report and returns the file path."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        # Sanitize strategy name for filename (Aggressive Windows Sanitization)
        clean_name = re.sub(r'[<>:"/\\|?*\']', '', hypothesis.strategy_name).replace(' ', '_').strip(' .')
        # Truncate if too long (Windows max path is ~260)
        clean_name = clean_name[:50]
        filename = f"HYPO_{clean_name}_{timestamp}.md"
        file_path = self.export_dir / filename

        status_emoji = "✅ APPROVED" if hypothesis.adversarial_score >= 0.7 and hypothesis.backtest_score >= 0.4 else "❌ REJECTED"

        md_content = f"""# Strategy Hypothesis: {hypothesis.strategy_name}
**Status:** {status_emoji}
**Adversarial Score:** {hypothesis.adversarial_score}
**Backtest Score:** {hypothesis.backtest_score}
**ID:** `{hypothesis.hypothesis_id}`
**Generated At:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## 1. Executive Summary
**Strategy Archetype:** {hypothesis.strategy_archetype.value}
**Strategy Type:** {hypothesis.strategy_type.value}
**Time Horizon:** {hypothesis.time_horizon_days} Days
**Economic Rationale:** 
{hypothesis.economic_rationale}

---

## 2. Execution Architecture (Trade Legs)
| Ticker | Type | Relative Weight | Entry Condition | Exit Condition |
|--------|------|-----------------|-----------------|----------------|
"""
        for leg in hypothesis.legs:
            md_content += f"| {leg.ticker} | {leg.leg_type.value} | {leg.relative_weight} | {leg.entry_condition or 'MKT'} | {leg.exit_condition or 'MKT'} |\n"

        md_content += f"""
---

## 3. Empirical Validation (Phase 5b Backtest)
> **Note:** This section shows how the proposed rules performed over the last 2 years.

### Key Performance Indicators (KPIs)
| Metric | Value |
|--------|-------|
| Win Rate | {hypothesis.backtest_metrics.get('win_rate', 0.0):.1%} |
| Avg Return | {hypothesis.backtest_metrics.get('avg_return', 0.0):.2%} |
| Sharpe Ratio | {hypothesis.backtest_metrics.get('sharpe', 0.0):.2f} |
| Portfolio Beta | {hypothesis.backtest_metrics.get('portfolio_beta', 0.0):.2f} |
| Total Triggers | {hypothesis.backtest_metrics.get('num_triggers', 0)} |

{hypothesis.validation_logs or "No backtest data available."}

---

## 4. Catalysts & Alpha Triggers
{self._format_list(hypothesis.catalysts)}

---

## 5. Risk Management & Invalidation
**Max Drawdown Tolerance:** {hypothesis.risk_metrics.max_drawdown_tolerance}%
**Invalidation Criteria:**
{self._format_list(hypothesis.invalidation_criteria)}

---

## 6. Adversarial Critique (Red Team Feedback)
> **Note:** This section is generated by the Phase 5 Gatekeeper to identify look-ahead bias and logical flaws.

{hypothesis.adversarial_feedback or "No critique available."}

---
*Generated by Strategy Ideation Engine v1.0*
"""
        
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(md_content)
            logger.info(f"Professional report exported to: {file_path}")
            return str(file_path)
        except Exception as e:
            logger.error(f"Failed to export report: {e}")
            return ""

    def _format_list(self, items: list) -> str:
        if not items: return "None listed."
        return "\n".join([f"- {i}" for i in items])
